create table if not exists public.perfil_negocio (
  id bigint generated by default as identity primary key,
  nombre_local text not null,
  mensaje_ticket text,
  moneda text not null default '$'
);

alter table public.perfil_negocio enable row level security;

create policy if not exists "anon_select_perfil_negocio"
on public.perfil_negocio
for select
to anon
using (true);

create policy if not exists "anon_insert_perfil_negocio"
on public.perfil_negocio
for insert
to anon
with check (true);

create policy if not exists "anon_update_perfil_negocio"
on public.perfil_negocio
for update
to anon
using (true)
with check (true);

insert into public.perfil_negocio (nombre_local, mensaje_ticket, moneda)
select 'ALMACÉN HONEY', 'Gracias por su compra.', '$'
where not exists (select 1 from public.perfil_negocio);
