create table if not exists public.clientes_deuda (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  nombre text not null,
  monto numeric(12,2) not null check (monto >= 0),
  fecha timestamptz not null default now()
);

alter table public.clientes_deuda enable row level security;

drop policy if exists deuda_select_own on public.clientes_deuda;
drop policy if exists deuda_insert_own on public.clientes_deuda;
drop policy if exists deuda_update_own on public.clientes_deuda;
drop policy if exists deuda_delete_own on public.clientes_deuda;

create policy deuda_select_own
on public.clientes_deuda
for select
to authenticated
using (user_id = auth.uid());

create policy deuda_insert_own
on public.clientes_deuda
for insert
to authenticated
with check (user_id = auth.uid());

create policy deuda_update_own
on public.clientes_deuda
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy deuda_delete_own
on public.clientes_deuda
for delete
to authenticated
using (user_id = auth.uid());
